import { Noto_Serif_JP } from "next/font/google";

const notoSerifJapanese = Noto_Serif_JP({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={notoSerifJapanese.className}>{children}</body>
    </html>
  );
}
