import { Noto_Serif_JP } from "next/font/google";

export const NotoSerifJapanese = Noto_Serif_JP({
  weight: "400",
  subsets:["latin"],
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={NotoSerifJapanese.className}>{children}</body> {/* Apply font globally */}
    </html>
  );
}